apiVersion: v1
kind: Secret
metadata:
  name: argoapi-secret
  labels:
    app: argoapi
type: Opaque
stringData:
  .env: |
    ARGOCD_SERVER=https://193.2.2.200
    ARGOCD_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjpsb2dpbiIsImV4cCI6MTc2NjY0MzU3OCwibmJmIjoxNzY2NTU3MTc4LCJpYXQiOjE3NjY1NTcxNzgsImp0aSI6ImMxYTliYjE2LWJmOWMtNDcyNy04Zjc0LTgwNDc1MmMxN2E4YiJ9.lyLZRbnsd1t-hPjpHJ7DfZftmT56DXPwRf66RUd2DXk
    TEAMS_WEBHOOK=https://your-teams-webhook-url
    HOST=0.0.0.0
    PORT=8899
