apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: argocd-develop-qoin-

namespace: default

commonLabels:
  app: argocd-develop-qoin

patches:
  - path: patch-deployment.yaml
