"""Jenkins API client wrapper using api4jenkins."""

import os
import sys
from typing import Optional, Dict, Any
from api4jenkins import Jenkins


def get_env_file_path() -> str:
    """Get the path to the .env file."""
    home = os.path.expanduser("~")
    ngen_j_dir = os.path.join(home, ".ngen-j")
    return os.path.join(ngen_j_dir, ".env")


def load_env_file() -> dict:
    """Load environment variables from ~/.ngen-j/.env file."""
    env_file = get_env_file_path()
    env_vars = {}

    if os.path.exists(env_file):
        try:
            with open(env_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#'):
                        if '=' in line:
                            key, value = line.split('=', 1)
                            env_vars[key.strip()] = value.strip()
        except Exception as e:
            print(f"Warning: Could not read .env file: {e}", file=sys.stderr)

    return env_vars


def save_env_file(env_vars: dict) -> bool:
    """Save environment variables to ~/.ngen-j/.env file."""
    env_file = get_env_file_path()

    try:
        # Create directory if it doesn't exist
        os.makedirs(os.path.dirname(env_file), exist_ok=True)

        with open(env_file, 'w') as f:
            f.write("# ngen-j Jenkins credentials\n")
            f.write("# Generated by: ngen-j login\n")
            f.write("\n")
            for key, value in env_vars.items():
                f.write(f"{key}={value}\n")

        # Set restrictive permissions (readable only by owner)
        os.chmod(env_file, 0o600)
        return True
    except Exception as e:
        print(f"Error: Could not save .env file: {e}", file=sys.stderr)
        return False


class JenkinsClient:
    """Jenkins API client wrapper."""

    def __init__(self):
        """Initialize Jenkins client from environment variables."""
        # Load from .env file first, then override with current env vars
        env_vars = load_env_file()
        self.url = os.getenv("JENKINS_URL") or env_vars.get("JENKINS_URL")
        self.user = os.getenv("JENKINS_USER") or env_vars.get("JENKINS_USER")
        self.token = os.getenv("JENKINS_TOKEN") or env_vars.get("JENKINS_TOKEN")
        self.auth = os.getenv("JENKINS_AUTH") or env_vars.get("JENKINS_AUTH")

        if not self.url:
            print("Error: JENKINS_URL environment variable is required", file=sys.stderr)
            print("Use 'ngen-j login' to set credentials", file=sys.stderr)
            sys.exit(1)

        # Determine authentication method
        auth_tuple = None
        if self.auth:
            # Use JENKINS_AUTH if provided (base64 encoded user:token)
            import base64
            try:
                decoded = base64.b64decode(self.auth).decode('utf-8')
                if ':' in decoded:
                    user, token = decoded.split(':', 1)
                    auth_tuple = (user, token)
            except Exception as e:
                print(f"Warning: Could not decode JENKINS_AUTH: {e}", file=sys.stderr)

        if not auth_tuple and self.user and self.token:
            auth_tuple = (self.user, self.token)

        if not auth_tuple:
            print("Error: Jenkins authentication required. Set JENKINS_USER and JENKINS_TOKEN, or JENKINS_AUTH", file=sys.stderr)
            print("Use 'ngen-j login' to set credentials", file=sys.stderr)
            sys.exit(1)

        try:
            self.client = Jenkins(self.url, auth=auth_tuple)
        except Exception as e:
            print(f"Error connecting to Jenkins: {e}", file=sys.stderr)
            sys.exit(1)
    
    def list_jobs(self) -> list:
        """List all Jenkins jobs."""
        try:
            jobs = []
            # Use the correct API method for api4jenkins
            for job in self.client.iter():
                jobs.append({
                    'name': job.name,
                    'url': job.url
                })
            return jobs
        except Exception as e:
            print(f"Error listing jobs: {e}", file=sys.stderr)
            sys.exit(1)
    
    def get_job(self, job_name: str) -> Dict[str, Any]:
        """Get job details."""
        try:
            job = self.client[job_name]
            return {
                'name': job.name,
                'url': job.url,
                'description': getattr(job, 'description', ''),
                'buildable': getattr(job, 'buildable', False),
            }
        except KeyError:
            print(f"Error: Job '{job_name}' not found", file=sys.stderr)
            sys.exit(1)
        except Exception as e:
            print(f"Error getting job: {e}", file=sys.stderr)
            sys.exit(1)
    
    def trigger_build(self, job_name: str, parameters: Optional[Dict[str, str]] = None) -> Dict[str, Any]:
        """Trigger a build for a job."""
        try:
            job = self.client[job_name]
            if parameters:
                queue_item = job.build(**parameters)
            else:
                queue_item = job.build()

            # api4jenkins returns a QueueItem, not a Build
            return {
                'queue_id': getattr(queue_item, 'id', 'unknown'),
                'url': getattr(queue_item, 'url', 'unknown'),
                'status': 'triggered'
            }
        except KeyError:
            print(f"Error: Job '{job_name}' not found", file=sys.stderr)
            sys.exit(1)
        except Exception as e:
            print(f"Error triggering build: {e}", file=sys.stderr)
            sys.exit(1)

